### ISSUE TITLE
embed response assumes that pids will have "islandora" shoulder

### ISSUE THREAD

**Issue by lo5an** [OULibraries/islandora_embed#7]
In the function getTranslatedUrl, we've hard-coded the assumption that repository content PIDs will start with "islandora", which breaks with our new "oku" content PIDs. I've adjusted this by hard coding the new PID shoulder in prod, but that will get overwritten the next time we deploy, and we should probably do a better fix that doesn't guess at the namespace of objects in any case.

**Comment by tdpearson** [comment]
Is this still an issue?

**Comment by lo5an** [comment]
Looks like this has been fixed.
